# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/will/SourceCode/Final-Year-Project/Workspace/ObjectDetector/UserInterface/misc/trainer.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1318, 1327)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("__central_widget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 1311, 1321))
        self.verticalLayoutWidget.setObjectName("__vertical_layout_widget")
        self.__trainer_main_layout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.__trainer_main_layout.setContentsMargins(0, 0, 0, 0)
        self.__trainer_main_layout.setObjectName("__trainer_main_layout")
        self.__trainer_directory_vertical_layout = QtWidgets.QVBoxLayout()
        self.__trainer_directory_vertical_layout.setObjectName("__trainer_directory_vertical_layout")
        self.__trainer_title_vertical_layout = QtWidgets.QVBoxLayout()
        self.__trainer_title_vertical_layout.setObjectName("__trainer_title_vertical_layout")
        self.__trainer_title = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.__trainer_title.setFont(font)
        self.__trainer_title.setAlignment(QtCore.Qt.AlignCenter)
        self.__trainer_title.setObjectName("__trainer_title")
        self.__trainer_title_vertical_layout.addWidget(self.__trainer_title)
        self.__trainer_directory_vertical_layout.addLayout(self.__trainer_title_vertical_layout)
        self.__trainer_directory_title = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.__trainer_directory_title.setFont(font)
        self.__trainer_directory_title.setAlignment(QtCore.Qt.AlignCenter)
        self.__trainer_directory_title.setObjectName("__trainer_directory_title")
        self.__trainer_directory_vertical_layout.addWidget(self.__trainer_directory_title)
        self.line_7 = QtWidgets.QFrame(self.verticalLayoutWidget)
        self.line_7.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.__trainer_directory_vertical_layout.addWidget(self.line_7)
        self.__trainer_directory_horizontal_layout = QtWidgets.QHBoxLayout()
        self.__trainer_directory_horizontal_layout.setObjectName("__trainer_directory_horizontal_layout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.__trainer_directory_horizontal_layout.addItem(spacerItem)
        self.__trainer_directory_field_ = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.__trainer_directory_field_.setAlignment(QtCore.Qt.AlignCenter)
        self.__trainer_directory_field_.setObjectName("__trainer_directory_field_")
        self.__trainer_directory_horizontal_layout.addWidget(self.__trainer_directory_field_)
        self.__trainer_directory_field = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.__trainer_directory_field.setMinimumSize(QtCore.QSize(700, 0))
        self.__trainer_directory_field.setAlignment(QtCore.Qt.AlignCenter)
        self.__trainer_directory_field.setObjectName("__trainer_directory_field")
        self.__trainer_directory_horizontal_layout.addWidget(self.__trainer_directory_field)
        self.__trainer_directory_open_nautilus_button = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.__trainer_directory_open_nautilus_button.setObjectName("__trainer_directory_open_nautilus_button")
        self.__trainer_directory_horizontal_layout.addWidget(self.__trainer_directory_open_nautilus_button)
        self.__trainer_directory_status = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.__trainer_directory_status.setAlignment(QtCore.Qt.AlignCenter)
        self.__trainer_directory_status.setObjectName("__trainer_directory_status")
        self.__trainer_directory_horizontal_layout.addWidget(self.__trainer_directory_status)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.__trainer_directory_horizontal_layout.addItem(spacerItem1)
        self.__trainer_directory_vertical_layout.addLayout(self.__trainer_directory_horizontal_layout)
        self.__trainer_main_layout.addLayout(self.__trainer_directory_vertical_layout)
        self.line_8 = QtWidgets.QFrame(self.verticalLayoutWidget)
        self.line_8.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.__trainer_main_layout.addWidget(self.line_8)
        self.__trainer_image_data_set_vertical_layout = QtWidgets.QVBoxLayout()
        self.__trainer_image_data_set_vertical_layout.setObjectName("__trainer_image_data_set_vertical_layout")
        self.__trainer_image_data_set_title = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.__trainer_image_data_set_title.setFont(font)
        self.__trainer_image_data_set_title.setAlignment(QtCore.Qt.AlignCenter)
        self.__trainer_image_data_set_title.setObjectName("__trainer_image_data_set_title")
        self.__trainer_image_data_set_vertical_layout.addWidget(self.__trainer_image_data_set_title)
        self.line = QtWidgets.QFrame(self.verticalLayoutWidget)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.__trainer_image_data_set_vertical_layout.addWidget(self.line)
        self.__trainer_image_data_set_directory_field_horizontal_layout = QtWidgets.QHBoxLayout()
        self.__trainer_image_data_set_directory_field_horizontal_layout.setObjectName("__trainer_image_data_set_directory_field_horizontal_layout")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.__trainer_image_data_set_directory_field_horizontal_layout.addItem(spacerItem2)
        self.__trainer_image_data_set_field_title = QtWidgets.QLabel(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.__trainer_image_data_set_field_title.sizePolicy().hasHeightForWidth())
        self.__trainer_image_data_set_field_title.setSizePolicy(sizePolicy)
        self.__trainer_image_data_set_field_title.setMinimumSize(QtCore.QSize(200, 0))
        self.__trainer_image_data_set_field_title.setObjectName("__trainer_image_data_set_field_title")
        self.__trainer_image_data_set_directory_field_horizontal_layout.addWidget(self.__trainer_image_data_set_field_title)
        self.__trainer_image_data_set_field = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.__trainer_image_data_set_field.sizePolicy().hasHeightForWidth())
        self.__trainer_image_data_set_field.setSizePolicy(sizePolicy)
        self.__trainer_image_data_set_field.setMinimumSize(QtCore.QSize(700, 0))
        self.__trainer_image_data_set_field.setAlignment(QtCore.Qt.AlignCenter)
        self.__trainer_image_data_set_field.setObjectName("__trainer_image_data_set_field")
        self.__trainer_image_data_set_directory_field_horizontal_layout.addWidget(self.__trainer_image_data_set_field)
        self.__trainer_image_data_set_field_open_nautilus_button = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.__trainer_image_data_set_field_open_nautilus_button.setObjectName("__trainer_image_data_set_field_open_nautilus_button")
        self.__trainer_image_data_set_directory_field_horizontal_layout.addWidget(self.__trainer_image_data_set_field_open_nautilus_button)
        self.__trainer_image_data_set_field_status = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.__trainer_image_data_set_field_status.setObjectName("__trainer_image_data_set_field_status")
        self.__trainer_image_data_set_directory_field_horizontal_layout.addWidget(self.__trainer_image_data_set_field_status)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.__trainer_image_data_set_directory_field_horizontal_layout.addItem(spacerItem3)
        self.__trainer_image_data_set_vertical_layout.addLayout(self.__trainer_image_data_set_directory_field_horizontal_layout)
        self.line_2 = QtWidgets.QFrame(self.verticalLayoutWidget)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.__trainer_image_data_set_vertical_layout.addWidget(self.line_2)
        self.__trainer_image_data_set_commit_to_training_directory_horizontal_layout = QtWidgets.QHBoxLayout()
        self.__trainer_image_data_set_commit_to_training_directory_horizontal_layout.setObjectName("__trainer_image_data_set_commit_to_training_directory_horizontal_layout")
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.__trainer_image_data_set_commit_to_training_directory_horizontal_layout.addItem(spacerItem4)
        self.__trainer_image_data_set_commit_to_training_directory = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.__trainer_image_data_set_commit_to_training_directory.setObjectName("__trainer_image_data_set_commit_to_training_directory")
        self.__trainer_image_data_set_commit_to_training_directory_horizontal_layout.addWidget(self.__trainer_image_data_set_commit_to_training_directory)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.__trainer_image_data_set_commit_to_training_directory_horizontal_layout.addItem(spacerItem5)
        self.__trainer_image_data_set_vertical_layout.addLayout(self.__trainer_image_data_set_commit_to_training_directory_horizontal_layout)
        self.line_6 = QtWidgets.QFrame(self.verticalLayoutWidget)
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.__trainer_image_data_set_vertical_layout.addWidget(self.line_6)
        self.__trainer_image_data_set_checks_vertical_layout = QtWidgets.QVBoxLayout()
        self.__trainer_image_data_set_checks_vertical_layout.setObjectName("__trainer_image_data_set_checks_vertical_layout")
        self.__trainer_image_data_set_file_format_check_title_horizontal_layout = QtWidgets.QHBoxLayout()
        self.__trainer_image_data_set_file_format_check_title_horizontal_layout.setObjectName("__trainer_image_data_set_file_format_check_title_horizontal_layout")
        self.__trainer_image_data_set_checks_title_label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.__trainer_image_data_set_checks_title_label.setMinimumSize(QtCore.QSize(300, 0))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.__trainer_image_data_set_checks_title_label.setFont(font)
        self.__trainer_image_data_set_checks_title_label.setAlignment(QtCore.Qt.AlignCenter)
        self.__trainer_image_data_set_checks_title_label.setObjectName("__trainer_image_data_set_checks_title_label")
        self.__trainer_image_data_set_file_format_check_title_horizontal_layout.addWidget(self.__trainer_image_data_set_checks_title_label)
        self.__trainer_image_data_set_checks_vertical_layout.addLayout(self.__trainer_image_data_set_file_format_check_title_horizontal_layout)
        self.__trainer_image_data_set_file_format_check_horizontal_layout = QtWidgets.QHBoxLayout()
        self.__trainer_image_data_set_file_format_check_horizontal_layout.setObjectName("__trainer_image_data_set_file_format_check_horizontal_layout")
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.__trainer_image_data_set_file_format_check_horizontal_layout.addItem(spacerItem6)
        self.__trainer_image_data_set_file_format_check_title = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.__trainer_image_data_set_file_format_check_title.setMinimumSize(QtCore.QSize(250, 0))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.__trainer_image_data_set_file_format_check_title.setFont(font)
        self.__trainer_image_data_set_file_format_check_title.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.__trainer_image_data_set_file_format_check_title.setObjectName("__trainer_image_data_set_file_format_check_title")
        self.__trainer_image_data_set_file_format_check_horizontal_layout.addWidget(self.__trainer_image_data_set_file_format_check_title)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.__trainer_image_data_set_file_format_check_horizontal_layout.addItem(spacerItem7)
        self.__trainer_image_data_set_file_format_check_status = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.__trainer_image_data_set_file_format_check_status.setMinimumSize(QtCore.QSize(300, 0))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.__trainer_image_data_set_file_format_check_status.setFont(font)
        self.__trainer_image_data_set_file_format_check_status.setStyleSheet("")
        self.__trainer_image_data_set_file_format_check_status.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.__trainer_image_data_set_file_format_check_status.setObjectName("__trainer_image_data_set_file_format_check_status")
        self.__trainer_image_data_set_file_format_check_horizontal_layout.addWidget(self.__trainer_image_data_set_file_format_check_status)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.__trainer_image_data_set_file_format_check_horizontal_layout.addItem(spacerItem8)
        self.__trainer_image_data_set_file_format_check_fix_button = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.__trainer_image_data_set_file_format_check_fix_button.setObjectName("__trainer_image_data_set_file_format_check_fix_button")
        self.__trainer_image_data_set_file_format_check_horizontal_layout.addWidget(self.__trainer_image_data_set_file_format_check_fix_button)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.__trainer_image_data_set_file_format_check_horizontal_layout.addItem(spacerItem9)
        self.__trainer_image_data_set_checks_vertical_layout.addLayout(self.__trainer_image_data_set_file_format_check_horizontal_layout)
        self.__trainer_image_data_set_file_number_of_images_check_horizontal_layout = QtWidgets.QHBoxLayout()
        self.__trainer_image_data_set_file_number_of_images_check_horizontal_layout.setObjectName("__trainer_image_data_set_file_number_of_images_check_horizontal_layout")
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.__trainer_image_data_set_file_number_of_images_check_horizontal_layout.addItem(spacerItem10)
        self.__trainer_image_data_set_number_of_images_check_title = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.__trainer_image_data_set_number_of_images_check_title.setMinimumSize(QtCore.QSize(250, 0))
        self.__trainer_image_data_set_number_of_images_check_title.setSizeIncrement(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.__trainer_image_data_set_number_of_images_check_title.setFont(font)
        self.__trainer_image_data_set_number_of_images_check_title.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.__trainer_image_data_set_number_of_images_check_title.setObjectName("__trainer_image_data_set_number_of_images_check_title")
        self.__trainer_image_data_set_file_number_of_images_check_horizontal_layout.addWidget(self.__trainer_image_data_set_number_of_images_check_title)
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.__trainer_image_data_set_file_number_of_images_check_horizontal_layout.addItem(spacerItem11)
        self.__trainer_image_data_set_file_number_of_images_check_status = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.__trainer_image_data_set_file_number_of_images_check_status.setMinimumSize(QtCore.QSize(300, 0))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.__trainer_image_data_set_file_number_of_images_check_status.setFont(font)
        self.__trainer_image_data_set_file_number_of_images_check_status.setStyleSheet("")
        self.__trainer_image_data_set_file_number_of_images_check_status.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.__trainer_image_data_set_file_number_of_images_check_status.setObjectName("__trainer_image_data_set_file_number_of_images_check_status")
        self.__trainer_image_data_set_file_number_of_images_check_horizontal_layout.addWidget(self.__trainer_image_data_set_file_number_of_images_check_status)
        spacerItem12 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.__trainer_image_data_set_file_number_of_images_check_horizontal_layout.addItem(spacerItem12)
        self.__trainer_image_data_set_number_of_images_check_fix_button = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.__trainer_image_data_set_number_of_images_check_fix_button.setObjectName("__trainer_image_data_set_number_of_images_check_fix_button")
        self.__trainer_image_data_set_file_number_of_images_check_horizontal_layout.addWidget(self.__trainer_image_data_set_number_of_images_check_fix_button)
        spacerItem13 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.__trainer_image_data_set_file_number_of_images_check_horizontal_layout.addItem(spacerItem13)
        self.__trainer_image_data_set_checks_vertical_layout.addLayout(self.__trainer_image_data_set_file_number_of_images_check_horizontal_layout)
        self.__trainer_image_data_set_file_image_size_check_horizontal_layout = QtWidgets.QHBoxLayout()
        self.__trainer_image_data_set_file_image_size_check_horizontal_layout.setObjectName("__trainer_image_data_set_file_image_size_check_horizontal_layout")
        spacerItem14 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.__trainer_image_data_set_file_image_size_check_horizontal_layout.addItem(spacerItem14)
        self.__trainer_image_data_set_image_size_check_title = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.__trainer_image_data_set_image_size_check_title.setMinimumSize(QtCore.QSize(250, 0))
        self.__trainer_image_data_set_image_size_check_title.setSizeIncrement(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.__trainer_image_data_set_image_size_check_title.setFont(font)
        self.__trainer_image_data_set_image_size_check_title.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.__trainer_image_data_set_image_size_check_title.setObjectName("__trainer_image_data_set_image_size_check_title")
        self.__trainer_image_data_set_file_image_size_check_horizontal_layout.addWidget(self.__trainer_image_data_set_image_size_check_title)
        spacerItem15 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.__trainer_image_data_set_file_image_size_check_horizontal_layout.addItem(spacerItem15)
        self.__trainer_image_data_set_image_size_check_status = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.__trainer_image_data_set_image_size_check_status.setMinimumSize(QtCore.QSize(300, 0))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.__trainer_image_data_set_image_size_check_status.setFont(font)
        self.__trainer_image_data_set_image_size_check_status.setStyleSheet("")
        self.__trainer_image_data_set_image_size_check_status.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.__trainer_image_data_set_image_size_check_status.setObjectName("__trainer_image_data_set_image_size_check_status")
        self.__trainer_image_data_set_file_image_size_check_horizontal_layout.addWidget(self.__trainer_image_data_set_image_size_check_status)
        spacerItem16 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.__trainer_image_data_set_file_image_size_check_horizontal_layout.addItem(spacerItem16)
        self.__trainer_image_data_set_image_size_check_fix_button = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.__trainer_image_data_set_image_size_check_fix_button.setObjectName("__trainer_image_data_set_image_size_check_fix_button")
        self.__trainer_image_data_set_file_image_size_check_horizontal_layout.addWidget(self.__trainer_image_data_set_image_size_check_fix_button)
        spacerItem17 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.__trainer_image_data_set_file_image_size_check_horizontal_layout.addItem(spacerItem17)
        self.__trainer_image_data_set_checks_vertical_layout.addLayout(self.__trainer_image_data_set_file_image_size_check_horizontal_layout)
        self.__trainer_image_data_set_file_corresponding_xml_check_horizontal_layout = QtWidgets.QHBoxLayout()
        self.__trainer_image_data_set_file_corresponding_xml_check_horizontal_layout.setObjectName("__trainer_image_data_set_file_corresponding_xml_check_horizontal_layout")
        spacerItem18 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.__trainer_image_data_set_file_corresponding_xml_check_horizontal_layout.addItem(spacerItem18)
        self.__trainer_image_data_set_corresponding_xml_files_check_title = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.__trainer_image_data_set_corresponding_xml_files_check_title.setMinimumSize(QtCore.QSize(250, 0))
        self.__trainer_image_data_set_corresponding_xml_files_check_title.setSizeIncrement(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.__trainer_image_data_set_corresponding_xml_files_check_title.setFont(font)
        self.__trainer_image_data_set_corresponding_xml_files_check_title.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.__trainer_image_data_set_corresponding_xml_files_check_title.setObjectName("__trainer_image_data_set_corresponding_xml_files_check_title")
        self.__trainer_image_data_set_file_corresponding_xml_check_horizontal_layout.addWidget(self.__trainer_image_data_set_corresponding_xml_files_check_title)
        spacerItem19 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.__trainer_image_data_set_file_corresponding_xml_check_horizontal_layout.addItem(spacerItem19)
        self.__trainer_image_data_set_file_corresponding_xml_files_check_status = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.__trainer_image_data_set_file_corresponding_xml_files_check_status.setMinimumSize(QtCore.QSize(300, 0))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.__trainer_image_data_set_file_corresponding_xml_files_check_status.setFont(font)
        self.__trainer_image_data_set_file_corresponding_xml_files_check_status.setStyleSheet("")
        self.__trainer_image_data_set_file_corresponding_xml_files_check_status.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.__trainer_image_data_set_file_corresponding_xml_files_check_status.setObjectName("__trainer_image_data_set_file_corresponding_xml_files_check_status")
        self.__trainer_image_data_set_file_corresponding_xml_check_horizontal_layout.addWidget(self.__trainer_image_data_set_file_corresponding_xml_files_check_status)
        spacerItem20 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.__trainer_image_data_set_file_corresponding_xml_check_horizontal_layout.addItem(spacerItem20)
        self.__trainer_image_data_set_corresponding_xml_files_check_fix_button = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.__trainer_image_data_set_corresponding_xml_files_check_fix_button.setObjectName("__trainer_image_data_set_corresponding_xml_files_check_fix_button")
        self.__trainer_image_data_set_file_corresponding_xml_check_horizontal_layout.addWidget(self.__trainer_image_data_set_corresponding_xml_files_check_fix_button)
        spacerItem21 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.__trainer_image_data_set_file_corresponding_xml_check_horizontal_layout.addItem(spacerItem21)
        self.__trainer_image_data_set_checks_vertical_layout.addLayout(self.__trainer_image_data_set_file_corresponding_xml_check_horizontal_layout)
        self.__trainer_image_data_set_file_xml_file_validity_check_horizontal_layout = QtWidgets.QHBoxLayout()
        self.__trainer_image_data_set_file_xml_file_validity_check_horizontal_layout.setObjectName("__trainer_image_data_set_file_xml_file_validity_check_horizontal_layout")
        spacerItem22 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.__trainer_image_data_set_file_xml_file_validity_check_horizontal_layout.addItem(spacerItem22)
        self.__trainer_image_data_set_xml_file_validity_check_title = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.__trainer_image_data_set_xml_file_validity_check_title.setMinimumSize(QtCore.QSize(250, 0))
        self.__trainer_image_data_set_xml_file_validity_check_title.setSizeIncrement(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.__trainer_image_data_set_xml_file_validity_check_title.setFont(font)
        self.__trainer_image_data_set_xml_file_validity_check_title.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.__trainer_image_data_set_xml_file_validity_check_title.setObjectName("__trainer_image_data_set_xml_file_validity_check_title")
        self.__trainer_image_data_set_file_xml_file_validity_check_horizontal_layout.addWidget(self.__trainer_image_data_set_xml_file_validity_check_title)
        spacerItem23 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.__trainer_image_data_set_file_xml_file_validity_check_horizontal_layout.addItem(spacerItem23)
        self.__trainer_image_data_set_file_xml_file_validity_check_status = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.__trainer_image_data_set_file_xml_file_validity_check_status.setMinimumSize(QtCore.QSize(300, 0))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.__trainer_image_data_set_file_xml_file_validity_check_status.setFont(font)
        self.__trainer_image_data_set_file_xml_file_validity_check_status.setStyleSheet("")
        self.__trainer_image_data_set_file_xml_file_validity_check_status.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.__trainer_image_data_set_file_xml_file_validity_check_status.setObjectName("__trainer_image_data_set_file_xml_file_validity_check_status")
        self.__trainer_image_data_set_file_xml_file_validity_check_horizontal_layout.addWidget(self.__trainer_image_data_set_file_xml_file_validity_check_status)
        spacerItem24 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.__trainer_image_data_set_file_xml_file_validity_check_horizontal_layout.addItem(spacerItem24)
        self.__trainer_image_data_set_xml_file_validity_check_fix_button = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.__trainer_image_data_set_xml_file_validity_check_fix_button.setObjectName("__trainer_image_data_set_xml_file_validity_check_fix_button")
        self.__trainer_image_data_set_file_xml_file_validity_check_horizontal_layout.addWidget(self.__trainer_image_data_set_xml_file_validity_check_fix_button)
        spacerItem25 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.__trainer_image_data_set_file_xml_file_validity_check_horizontal_layout.addItem(spacerItem25)
        self.__trainer_image_data_set_checks_vertical_layout.addLayout(self.__trainer_image_data_set_file_xml_file_validity_check_horizontal_layout)
        self.__trainer_image_data_set_vertical_layout.addLayout(self.__trainer_image_data_set_checks_vertical_layout)
        self.line_3 = QtWidgets.QFrame(self.verticalLayoutWidget)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.__trainer_image_data_set_vertical_layout.addWidget(self.line_3)
        self.__trainer_image_data_set_split_vertical_layout = QtWidgets.QVBoxLayout()
        self.__trainer_image_data_set_split_vertical_layout.setObjectName("__trainer_image_data_set_split_vertical_layout")
        self.__trainer_image_data_set_split_title = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.__trainer_image_data_set_split_title.setFont(font)
        self.__trainer_image_data_set_split_title.setAlignment(QtCore.Qt.AlignCenter)
        self.__trainer_image_data_set_split_title.setObjectName("__trainer_image_data_set_split_title")
        self.__trainer_image_data_set_split_vertical_layout.addWidget(self.__trainer_image_data_set_split_title)
        self.__trainer_image_data_set_horizontal_layout = QtWidgets.QHBoxLayout()
        self.__trainer_image_data_set_horizontal_layout.setObjectName("__trainer_image_data_set_horizontal_layout")
        spacerItem26 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.__trainer_image_data_set_horizontal_layout.addItem(spacerItem26)
        self.__trainer_image_data_set_split_field_title = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.__trainer_image_data_set_split_field_title.setMinimumSize(QtCore.QSize(150, 0))
        self.__trainer_image_data_set_split_field_title.setSizeIncrement(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.__trainer_image_data_set_split_field_title.setFont(font)
        self.__trainer_image_data_set_split_field_title.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.__trainer_image_data_set_split_field_title.setObjectName("__trainer_image_data_set_split_field_title")
        self.__trainer_image_data_set_horizontal_layout.addWidget(self.__trainer_image_data_set_split_field_title)
        self.__trainer_image_data_set_split_percentage_field = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.__trainer_image_data_set_split_percentage_field.setMinimumSize(QtCore.QSize(700, 0))
        self.__trainer_image_data_set_split_percentage_field.setInputMask("")
        self.__trainer_image_data_set_split_percentage_field.setAlignment(QtCore.Qt.AlignCenter)
        self.__trainer_image_data_set_split_percentage_field.setObjectName("__trainer_image_data_set_split_percentage_field")
        self.__trainer_image_data_set_horizontal_layout.addWidget(self.__trainer_image_data_set_split_percentage_field)
        self.__trainer_image_data_set_split_button = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.__trainer_image_data_set_split_button.setMinimumSize(QtCore.QSize(150, 0))
        self.__trainer_image_data_set_split_button.setObjectName("__trainer_image_data_set_split_button")
        self.__trainer_image_data_set_horizontal_layout.addWidget(self.__trainer_image_data_set_split_button)
        spacerItem27 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.__trainer_image_data_set_horizontal_layout.addItem(spacerItem27)
        self.__trainer_image_data_set_split_vertical_layout.addLayout(self.__trainer_image_data_set_horizontal_layout)
        self.__trainer_image_data_set_vertical_layout.addLayout(self.__trainer_image_data_set_split_vertical_layout)
        self.line_9 = QtWidgets.QFrame(self.verticalLayoutWidget)
        self.line_9.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_9.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_9.setObjectName("line_9")
        self.__trainer_image_data_set_vertical_layout.addWidget(self.line_9)
        self.__trainer_image_data_commit_to_tensorflow = QtWidgets.QVBoxLayout()
        self.__trainer_image_data_commit_to_tensorflow.setObjectName("__trainer_image_data_commit_to_tensorflow")
        self.__trainer_image_data_convert_to_tf_record = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.__trainer_image_data_convert_to_tf_record.setFont(font)
        self.__trainer_image_data_convert_to_tf_record.setAlignment(QtCore.Qt.AlignCenter)
        self.__trainer_image_data_convert_to_tf_record.setObjectName("__trainer_image_data_convert_to_tf_record")
        self.__trainer_image_data_commit_to_tensorflow.addWidget(self.__trainer_image_data_convert_to_tf_record)
        self.__trainer_image_data_commit_to_tensorflow_horizontal_layout = QtWidgets.QHBoxLayout()
        self.__trainer_image_data_commit_to_tensorflow_horizontal_layout.setObjectName("__trainer_image_data_commit_to_tensorflow_horizontal_layout")
        spacerItem28 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.__trainer_image_data_commit_to_tensorflow_horizontal_layout.addItem(spacerItem28)
        self.__trainer_image_data_convert_to_tf_record_button = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.__trainer_image_data_convert_to_tf_record_button.setObjectName("__trainer_image_data_convert_to_tf_record_button")
        self.__trainer_image_data_commit_to_tensorflow_horizontal_layout.addWidget(self.__trainer_image_data_convert_to_tf_record_button)
        self.__trainer_image_data_convert_to_tf_record_label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.__trainer_image_data_convert_to_tf_record_label.setMinimumSize(QtCore.QSize(150, 0))
        self.__trainer_image_data_convert_to_tf_record_label.setObjectName("__trainer_image_data_convert_to_tf_record_label")
        self.__trainer_image_data_commit_to_tensorflow_horizontal_layout.addWidget(self.__trainer_image_data_convert_to_tf_record_label)
        spacerItem29 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.__trainer_image_data_commit_to_tensorflow_horizontal_layout.addItem(spacerItem29)
        self.__trainer_image_data_commit_to_tensorflow.addLayout(self.__trainer_image_data_commit_to_tensorflow_horizontal_layout)
        self.__trainer_image_data_set_vertical_layout.addLayout(self.__trainer_image_data_commit_to_tensorflow)
        self.__trainer_main_layout.addLayout(self.__trainer_image_data_set_vertical_layout)
        self.line_5 = QtWidgets.QFrame(self.verticalLayoutWidget)
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.__trainer_main_layout.addWidget(self.line_5)
        self.__trainer_model_vertical_layout = QtWidgets.QVBoxLayout()
        self.__trainer_model_vertical_layout.setObjectName("__trainer_model_vertical_layout")
        self.__trainer_model_selection_title = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.__trainer_model_selection_title.setFont(font)
        self.__trainer_model_selection_title.setAlignment(QtCore.Qt.AlignCenter)
        self.__trainer_model_selection_title.setObjectName("__trainer_model_selection_title")
        self.__trainer_model_vertical_layout.addWidget(self.__trainer_model_selection_title)
        self.__trainer_field_horizontal_layout = QtWidgets.QHBoxLayout()
        self.__trainer_field_horizontal_layout.setObjectName("__trainer_field_horizontal_layout")
        spacerItem30 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.__trainer_field_horizontal_layout.addItem(spacerItem30)
        self.__trainer_model_field_title = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.__trainer_model_field_title.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.__trainer_model_field_title.setObjectName("__trainer_model_field_title")
        self.__trainer_field_horizontal_layout.addWidget(self.__trainer_model_field_title)
        self.__trainer_model_field = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.__trainer_model_field.setMinimumSize(QtCore.QSize(700, 0))
        self.__trainer_model_field.setObjectName("__trainer_model_field")
        self.__trainer_field_horizontal_layout.addWidget(self.__trainer_model_field)
        self.__trainer_model_field_open_nautilus_button = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.__trainer_model_field_open_nautilus_button.setObjectName("__trainer_model_field_open_nautilus_button")
        self.__trainer_field_horizontal_layout.addWidget(self.__trainer_model_field_open_nautilus_button)
        self.__trainer_model_field_status = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.__trainer_model_field_status.setObjectName("__trainer_model_field_status")
        self.__trainer_field_horizontal_layout.addWidget(self.__trainer_model_field_status)
        spacerItem31 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.__trainer_field_horizontal_layout.addItem(spacerItem31)
        self.__trainer_model_vertical_layout.addLayout(self.__trainer_field_horizontal_layout)
        self.__trainer_config_horizontal_layout = QtWidgets.QHBoxLayout()
        self.__trainer_config_horizontal_layout.setObjectName("__trainer_config_horizontal_layout")
        spacerItem32 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.__trainer_config_horizontal_layout.addItem(spacerItem32)
        self.__trainer_config_field_title = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.__trainer_config_field_title.setObjectName("__trainer_config_field_title")
        self.__trainer_config_horizontal_layout.addWidget(self.__trainer_config_field_title)
        self.__trainer_config_field = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.__trainer_config_field.setMinimumSize(QtCore.QSize(700, 0))
        self.__trainer_config_field.setObjectName("__trainer_config_field")
        self.__trainer_config_horizontal_layout.addWidget(self.__trainer_config_field)
        self.__trainer_config_field_open_nautilus_button = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.__trainer_config_field_open_nautilus_button.setObjectName("__trainer_config_field_open_nautilus_button")
        self.__trainer_config_horizontal_layout.addWidget(self.__trainer_config_field_open_nautilus_button)
        self.__trainer_config_field_status = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.__trainer_config_field_status.setObjectName("__trainer_config_field_status")
        self.__trainer_config_horizontal_layout.addWidget(self.__trainer_config_field_status)
        spacerItem33 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.__trainer_config_horizontal_layout.addItem(spacerItem33)
        self.__trainer_model_vertical_layout.addLayout(self.__trainer_config_horizontal_layout)
        self.__trainer_model_commit_horizontal_layout = QtWidgets.QHBoxLayout()
        self.__trainer_model_commit_horizontal_layout.setObjectName("__trainer_model_commit_horizontal_layout")
        spacerItem34 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.__trainer_model_commit_horizontal_layout.addItem(spacerItem34)
        self.__trainer_model_commit_to_training_directory_button = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.__trainer_model_commit_to_training_directory_button.setObjectName("__trainer_model_commit_to_training_directory_button")
        self.__trainer_model_commit_horizontal_layout.addWidget(self.__trainer_model_commit_to_training_directory_button)
        self.__trainer_model_commit_to_training_directory_status = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.__trainer_model_commit_to_training_directory_status.setObjectName("__trainer_model_commit_to_training_directory_status")
        self.__trainer_model_commit_horizontal_layout.addWidget(self.__trainer_model_commit_to_training_directory_status)
        spacerItem35 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.__trainer_model_commit_horizontal_layout.addItem(spacerItem35)
        self.__trainer_model_vertical_layout.addLayout(self.__trainer_model_commit_horizontal_layout)
        self.__trainer_main_layout.addLayout(self.__trainer_model_vertical_layout)
        self.line_4 = QtWidgets.QFrame(self.verticalLayoutWidget)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.__trainer_main_layout.addWidget(self.line_4)
        self.__trainer_control_panel_vertical_layout = QtWidgets.QVBoxLayout()
        self.__trainer_control_panel_vertical_layout.setObjectName("__trainer_control_panel_vertical_layout")
        self.__trainer_control_panel_horizontal_layout = QtWidgets.QHBoxLayout()
        self.__trainer_control_panel_horizontal_layout.setObjectName("__trainer_control_panel_horizontal_layout")
        self.__trainer_control_panel_controls_vertical_layout = QtWidgets.QVBoxLayout()
        self.__trainer_control_panel_controls_vertical_layout.setObjectName("__trainer_control_panel_controls_vertical_layout")
        self.__trainer_control_panel_start_button = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.__trainer_control_panel_start_button.setObjectName("__trainer_control_panel_start_button")
        self.__trainer_control_panel_controls_vertical_layout.addWidget(self.__trainer_control_panel_start_button)
        self.__trainer_control_panel_open_tensorboard_button = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.__trainer_control_panel_open_tensorboard_button.setObjectName("__trainer_control_panel_open_tensor_board_button")
        self.__trainer_control_panel_controls_vertical_layout.addWidget(self.__trainer_control_panel_open_tensorboard_button)
        self.__trainer_control_panel_stop_button = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.__trainer_control_panel_stop_button.setObjectName("__trainer_control_panel_stop_button")
        self.__trainer_control_panel_controls_vertical_layout.addWidget(self.__trainer_control_panel_stop_button)
        self.__trainer_control_panel_export_inference_graph = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.__trainer_control_panel_export_inference_graph.setObjectName("__trainer_control_panel_export_inference_graph_button")
        self.__trainer_control_panel_controls_vertical_layout.addWidget(self.__trainer_control_panel_export_inference_graph)
        self.__trainer_control_panel_horizontal_layout.addLayout(self.__trainer_control_panel_controls_vertical_layout)
        self.__trainer_control_panel_output_vertical_layout = QtWidgets.QVBoxLayout()
        self.__trainer_control_panel_output_vertical_layout.setObjectName("__trainer_control_panel_output_vertical_layout")
        self.__trainer_control_panel_output_area = QtWidgets.QTextEdit(self.verticalLayoutWidget)
        self.__trainer_control_panel_output_area.setStyleSheet("background-color:black;\n"
"color:white;")
        self.__trainer_control_panel_output_area.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.__trainer_control_panel_output_area.setObjectName("__trainer_control_panel_output_area")
        self.__trainer_control_panel_output_vertical_layout.addWidget(self.__trainer_control_panel_output_area)
        self.__trainer_control_panel_horizontal_layout.addLayout(self.__trainer_control_panel_output_vertical_layout)
        self.__trainer_control_panel_vertical_layout.addLayout(self.__trainer_control_panel_horizontal_layout)
        self.__trainer_main_layout.addLayout(self.__trainer_control_panel_vertical_layout)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.__trainer_title.setText(_translate("MainWindow", "Trainer"))
        self.__trainer_directory_title.setText(_translate("MainWindow", "Training Directory"))
        self.__trainer_directory_field_.setText(_translate("MainWindow", "Training Directory"))
        self.__trainer_directory_open_nautilus_button.setText(_translate("MainWindow", "..."))
        self.__trainer_directory_status.setText(_translate("MainWindow", "No Directory set"))
        self.__trainer_image_data_set_title.setText(_translate("MainWindow", "Image Dataset"))
        self.__trainer_image_data_set_field_title.setText(_translate("MainWindow", "Directory Of Image Dataset"))
        self.__trainer_image_data_set_field_open_nautilus_button.setText(_translate("MainWindow", "..."))
        self.__trainer_image_data_set_field_status.setText(_translate("MainWindow", "No Directory Set"))
        self.__trainer_image_data_set_commit_to_training_directory.setText(_translate("MainWindow", "Commit Dataset to Training Directory"))
        self.__trainer_image_data_set_checks_title_label.setText(_translate("MainWindow", "Checking Dataset"))
        self.__trainer_image_data_set_file_format_check_title.setText(_translate("MainWindow", "File Format:"))
        self.__trainer_image_data_set_file_format_check_status.setText(_translate("MainWindow", "Checking..."))
        self.__trainer_image_data_set_file_format_check_fix_button.setText(_translate("MainWindow", "Fix"))
        self.__trainer_image_data_set_number_of_images_check_title.setText(_translate("MainWindow", "Number Of Images:"))
        self.__trainer_image_data_set_file_number_of_images_check_status.setText(_translate("MainWindow", "Waiting for previous Check."))
        self.__trainer_image_data_set_number_of_images_check_fix_button.setText(_translate("MainWindow", "Fix"))
        self.__trainer_image_data_set_image_size_check_title.setText(_translate("MainWindow", "Image Size:"))
        self.__trainer_image_data_set_image_size_check_status.setText(_translate("MainWindow", "Waiting for previous Check."))
        self.__trainer_image_data_set_image_size_check_fix_button.setText(_translate("MainWindow", "Fix"))
        self.__trainer_image_data_set_corresponding_xml_files_check_title.setText(_translate("MainWindow", "Corresponding XML files:"))
        self.__trainer_image_data_set_file_corresponding_xml_files_check_status.setText(_translate("MainWindow", "Waiting for previous Check."))
        self.__trainer_image_data_set_corresponding_xml_files_check_fix_button.setText(_translate("MainWindow", "Fix"))
        self.__trainer_image_data_set_xml_file_validity_check_title.setText(_translate("MainWindow", "XML File Validity:"))
        self.__trainer_image_data_set_file_xml_file_validity_check_status.setText(_translate("MainWindow", "Waiting for previous Check."))
        self.__trainer_image_data_set_xml_file_validity_check_fix_button.setText(_translate("MainWindow", "Fix"))
        self.__trainer_image_data_set_split_title.setText(_translate("MainWindow", "Splitting the data set into test and train sets"))
        self.__trainer_image_data_set_split_field_title.setText(_translate("MainWindow", "Percentage of test images:"))
        self.__trainer_image_data_set_split_percentage_field.setText(_translate("MainWindow", "10"))
        self.__trainer_image_data_set_split_button.setText(_translate("MainWindow", "Split"))
        self.__trainer_image_data_convert_to_tf_record.setText(_translate("MainWindow", "Convert to TF Record"))
        self.__trainer_image_data_convert_to_tf_record_button.setText(_translate("MainWindow", "Convert"))
        self.__trainer_image_data_convert_to_tf_record_label.setText(_translate("MainWindow", "Waiting for Checks to Clear"))
        self.__trainer_model_selection_title.setText(_translate("MainWindow", "Model Selection"))
        self.__trainer_model_field_title.setText(_translate("MainWindow", "Model Directory:"))
        self.__trainer_model_field_open_nautilus_button.setText(_translate("MainWindow", "..."))
        self.__trainer_model_field_status.setText(_translate("MainWindow", "No Directory Set"))
        self.__trainer_config_field_title.setText(_translate("MainWindow", "Model Config File:"))
        self.__trainer_config_field_open_nautilus_button.setText(_translate("MainWindow", "..."))
        self.__trainer_config_field_status.setText(_translate("MainWindow", "No File Path Set"))
        self.__trainer_model_commit_to_training_directory_button.setText(_translate("MainWindow", "Commit Model"))
        self.__trainer_model_commit_to_training_directory_status.setText(_translate("MainWindow", "Waiting for models"))
        self.__trainer_control_panel_start_button.setText(_translate("MainWindow", "Start Training"))
        self.__trainer_control_panel_open_tensorboard_button.setText(_translate("MainWindow", "Open Tensorboard"))
        self.__trainer_control_panel_stop_button.setText(_translate("MainWindow", "Stop Training"))
        self.__trainer_control_panel_export_inference_graph.setText(_translate("MainWindow", "Export Inference Graph"))
        self.__trainer_control_panel_output_area.setPlaceholderText(_translate("MainWindow", "Waiting to start....."))



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

